services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
    develop:
      watch:
        - action: sync
          path: .
          target: /code
    command: gunicorn -w 4 -b 0.0.0.0:8000 app:app
  redis:
    image: "redis:alpine"
    volumes:
      - redis-db:/data
volumes:
  redis-db: